version: "3"
services:
  mongo0:
    container_name: mongo0
    image: mongo
    volumes:
      - ./db/mongo-data/mongo0:/data/db
      - ./db/mongod.conf:/etc/mongod.conf
      - ./mongodb.key:/data/mongodb.key
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - mongoNet
    restart: always
    command: mongod --replSet rs0 -f /etc/mongod.conf --keyFile /data/mongodb.key
    entrypoint:
      - bash
      - -c
      - |
        chmod 400 /data/mongodb.key
        chown 999:999 /data/mongodb.key
        exec docker-entrypoint.sh $$@
    # entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "-f", "/etc/mongod.conf", "--replSet", "rs0" ]
  mongo1:
    container_name: mongo1
    image: mongo
    volumes:
      - ./db/mongo-data/mongo1:/data/db
      - ./db/mongod.conf:/etc/mongod.conf
      - ./mongodb.key:/data/mongodb.key
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - mongoNet
    restart: always
    command: mongod --replSet rs0 -f /etc/mongod.conf --keyFile /data/mongodb.key
    entrypoint:
      - bash
      - -c
      - |
        chmod 400 /data/mongodb.key
        chown 999:999 /data/mongodb.key
        exec docker-entrypoint.sh $$@
    # entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "-f", "/etc/mongod.conf", "--replSet", "rs0" ]
  mongo2:
    container_name: mongo2
    image: mongo
    volumes:
      - ./db/mongo-data/mongo2:/data/db
      - ./db/mongod.conf:/etc/mongod.conf
      - ./mongodb.key:/data/mongodb.key
    ports:
      - 27019:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - mongoNet
    restart: always
    command: mongod --replSet rs0 -f /etc/mongod.conf --keyFile /data/mongodb.key
    entrypoint:
      - bash
      - -c
      - |
        chmod 400 /data/mongodb.key
        chown 999:999 /data/mongodb.key
        exec docker-entrypoint.sh $$@
    # entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "-f", "/etc/mongod.conf", "--replSet", "rs0" ]

networks:
  mongoNet:
    driver: bridge